// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Error {
    #[prost(enumeration = "ErrorCode", tag = "1")]
    pub code: i32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ErrorCode {
    Unspecified = 0,
    NotFound = 1,
    InvalidArgument = 2,
    PermissionDenied = 3,
    Internal = 4,
}
impl ErrorCode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "ERROR_CODE_UNSPECIFIED",
            Self::NotFound => "ERROR_CODE_NOT_FOUND",
            Self::InvalidArgument => "ERROR_CODE_INVALID_ARGUMENT",
            Self::PermissionDenied => "ERROR_CODE_PERMISSION_DENIED",
            Self::Internal => "ERROR_CODE_INTERNAL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ERROR_CODE_UNSPECIFIED" => Some(Self::Unspecified),
            "ERROR_CODE_NOT_FOUND" => Some(Self::NotFound),
            "ERROR_CODE_INVALID_ARGUMENT" => Some(Self::InvalidArgument),
            "ERROR_CODE_PERMISSION_DENIED" => Some(Self::PermissionDenied),
            "ERROR_CODE_INTERNAL" => Some(Self::Internal),
            _ => None,
        }
    }
}
