// Auto-generated category configuration
// This file is generated by scripts/generate-docs-registry.js during prebuild

export const CATEGORY_ORDER = ['general', 'about', 'credits', 'workflows'] as const;

export const CATEGORY_ICONS: Record<string, string> = {
    'general': '📚',
    'about': '📋',
    'credits': '👥',
    'workflows': '⚡'
} as const;

export const CATEGORY_NAMES: Record<string, string> = {
    'general': 'General',
    'about': 'About',
    'credits': 'Credits',
    'workflows': 'Workflows'
} as const;

export const PREFERRED_DEFAULT_DOCS = ['home', 'index', 'getting-started', 'ethics'] as const;

export type DocCategory = typeof CATEGORY_ORDER[number];
