// Auto-generated docs registry
// This file is generated by scripts/generate-docs-registry.js during prebuild
// Categories are defined in ../components/docs/constants/docCategories.generated.ts

import type { DocCategory } from '@/components/docs/constants/docCategories.generated';

import about_community_managers from '@/assets/docs/about/community-managers.md';
import about_contributing from '@/assets/docs/about/contributing.md';
import about_data_collection from '@/assets/docs/about/data-collection.md';
import about_designers from '@/assets/docs/about/designers.md';
import about_developers from '@/assets/docs/about/developers.md';
import about_discussions from '@/assets/docs/about/discussions.md';
import about_documenting from '@/assets/docs/about/documenting.md';
import about_goals from '@/assets/docs/about/goals.md';
import about from '@/assets/docs/about/index.md';
import about_license from '@/assets/docs/about/license.md';
import about_project_managers from '@/assets/docs/about/project-managers.md';
import about_reporting_issues from '@/assets/docs/about/reporting-issues.md';
import about_submitting_feedback from '@/assets/docs/about/submitting-feedback.md';
import credits from '@/assets/docs/credits/index.md';
import credits_research from '@/assets/docs/credits/research.md';
import ethics from '@/assets/docs/ethics.md';
import home from '@/assets/docs/index.md';
import workflows_image_processing from '@/assets/docs/workflows/image-processing.md';
import workflows from '@/assets/docs/workflows/index.md';

export const docsModules = {
  'about/community-managers': about_community_managers,
  'about/contributing': about_contributing,
  'about/data-collection': about_data_collection,
  'about/designers': about_designers,
  'about/developers': about_developers,
  'about/discussions': about_discussions,
  'about/documenting': about_documenting,
  'about/goals': about_goals,
  'about': about,
  'about/license': about_license,
  'about/project-managers': about_project_managers,
  'about/reporting-issues': about_reporting_issues,
  'about/submitting-feedback': about_submitting_feedback,
  'credits': credits,
  'credits/research': credits_research,
  'ethics': ethics,
  'home': home,
  'workflows/image-processing': workflows_image_processing,
  'workflows': workflows
};

export const docsMetadata = [
  {
    slug: 'about/community-managers',
    filePath: 'about/community-managers.md',
    category: 'about'
  },
  {
    slug: 'about/contributing',
    filePath: 'about/contributing.md',
    category: 'about'
  },
  {
    slug: 'about/data-collection',
    filePath: 'about/data-collection.md',
    category: 'about'
  },
  {
    slug: 'about/designers',
    filePath: 'about/designers.md',
    category: 'about'
  },
  {
    slug: 'about/developers',
    filePath: 'about/developers.md',
    category: 'about'
  },
  {
    slug: 'about/discussions',
    filePath: 'about/discussions.md',
    category: 'about'
  },
  {
    slug: 'about/documenting',
    filePath: 'about/documenting.md',
    category: 'about'
  },
  {
    slug: 'about/goals',
    filePath: 'about/goals.md',
    category: 'about'
  },
  {
    slug: 'about',
    filePath: 'about/index.md',
    category: 'about'
  },
  {
    slug: 'about/license',
    filePath: 'about/license.md',
    category: 'about'
  },
  {
    slug: 'about/project-managers',
    filePath: 'about/project-managers.md',
    category: 'about'
  },
  {
    slug: 'about/reporting-issues',
    filePath: 'about/reporting-issues.md',
    category: 'about'
  },
  {
    slug: 'about/submitting-feedback',
    filePath: 'about/submitting-feedback.md',
    category: 'about'
  },
  {
    slug: 'credits',
    filePath: 'credits/index.md',
    category: 'credits'
  },
  {
    slug: 'credits/research',
    filePath: 'credits/research.md',
    category: 'credits'
  },
  {
    slug: 'ethics',
    filePath: 'ethics.md',
    category: 'general'
  },
  {
    slug: 'home',
    filePath: 'index.md',
    category: 'general'
  },
  {
    slug: 'workflows/image-processing',
    filePath: 'workflows/image-processing.md',
    category: 'workflows'
  },
  {
    slug: 'workflows',
    filePath: 'workflows/index.md',
    category: 'workflows'
  }
];

export type DocMetadata = {
  slug: string;
  filePath: string;
  category: DocCategory;
  nestedCategory?: string;
};
