[package]
name = "f2"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
    "crates/auth-svc",
#    "crates/cargo-docker",
    "crates/utils"]

[[bin]]
name = "auth-svc"
path = "crates/auth-svc/src/main.rs"
