apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f supabase.yaml convert
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: functions
  name: functions
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: functions
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f supabase.yaml convert
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: functions
    spec:
      containers:
        - args:
            - start
            - --main-service
            - /home/deno/functions/main
          env:
            - name: JWT_SECRET
            - name: SUPABASE_ANON_KEY
            - name: SUPABASE_DB_URL
              value: postgresql://postgres:@:/
            - name: SUPABASE_SERVICE_ROLE_KEY
            - name: SUPABASE_URL
              value: http://kong:8000
            - name: VERIFY_JWT
          image: supabase/edge-runtime:v1.67.4
          name: supabase-edge-functions
          volumeMounts:
            - mountPath: /home/deno/functions
              name: functions-claim0
      restartPolicy: Always
      volumes:
        - name: functions-claim0
          persistentVolumeClaim:
            claimName: functions-claim0
