apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f supabase.yaml convert
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: meta
  name: meta
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: meta
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f supabase.yaml convert
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: meta
    spec:
      containers:
        - env:
            - name: PG_META_DB_HOST
            - name: PG_META_DB_NAME
            - name: PG_META_DB_PASSWORD
            - name: PG_META_DB_PORT
            - name: PG_META_DB_USER
              value: supabase_admin
            - name: PG_META_PORT
              value: "8080"
          image: supabase/postgres-meta:v0.89.3
          name: supabase-meta
      restartPolicy: Always
