apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f supabase.yaml convert
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: realtime
  name: realtime
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: realtime
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f supabase.yaml convert
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: realtime
    spec:
      containers:
        - env:
            - name: API_JWT_SECRET
            - name: APP_NAME
              value: realtime
            - name: DB_AFTER_CONNECT_QUERY
              value: SET search_path TO _realtime
            - name: DB_ENC_KEY
              value: supabaserealtime
            - name: DB_HOST
            - name: DB_NAME
            - name: DB_PASSWORD
            - name: DB_PORT
            - name: DB_USER
              value: supabase_admin
            - name: DNS_NODES
              value: ''''''
            - name: ERL_AFLAGS
              value: -proto_dist inet_tcp
            - name: PORT
              value: "4000"
            - name: RLIMIT_NOFILE
              value: "10000"
            - name: RUN_JANITOR
              value: "true"
            - name: SECRET_KEY_BASE
            - name: SEED_SELF_HOST
              value: "true"
          image: supabase/realtime:v2.34.47
          livenessProbe:
            exec:
              command:
                - curl
                - -sSfL
                - --head
                - -o
                - /dev/null
                - -H
                - 'Authorization: Bearer '
                - http://localhost:4000/api/tenants/realtime-dev/health
            failureThreshold: 3
            periodSeconds: 5
            timeoutSeconds: 5
          name: realtime-dev.supabase-realtime
      restartPolicy: Always
