apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f supabase.yaml convert
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: studio
  name: studio
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: studio
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f supabase.yaml convert
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: studio
    spec:
      containers:
        - env:
            - name: AUTH_JWT_SECRET
            - name: DEFAULT_ORGANIZATION_NAME
            - name: DEFAULT_PROJECT_NAME
            - name: LOGFLARE_PRIVATE_ACCESS_TOKEN
            - name: LOGFLARE_URL
              value: http://analytics:4000
            - name: NEXT_ANALYTICS_BACKEND_PROVIDER
              value: postgres
            - name: NEXT_PUBLIC_ENABLE_LOGS
              value: "true"
            - name: OPENAI_API_KEY
            - name: POSTGRES_PASSWORD
            - name: STUDIO_PG_META_URL
              value: http://meta:8080
            - name: SUPABASE_ANON_KEY
            - name: SUPABASE_PUBLIC_URL
            - name: SUPABASE_SERVICE_KEY
            - name: SUPABASE_URL
              value: http://kong:8000
          image: supabase/studio:2025.06.02-sha-8f2993d
          livenessProbe:
            exec:
              command:
                - node
                - -e
                - fetch('http://studio:3000/api/platform/profile').then((r) => {if (r.status !== 200) throw new Error(r.status)})
            failureThreshold: 3
            periodSeconds: 5
            timeoutSeconds: 10
          name: supabase-studio
      restartPolicy: Always
