apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f supabase.yaml convert
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: supavisor
  name: supavisor
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: supavisor
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f supabase.yaml convert
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: supavisor
    spec:
      containers:
        - args:
            - /bin/sh
            - -c
            - /app/bin/migrate && /app/bin/supavisor eval "$()(cat /etc/pooler/pooler.exs)" && /app/bin/server
          env:
            - name: API_JWT_SECRET
            - name: CLUSTER_POSTGRES
              value: "true"
            - name: DATABASE_URL
              value: ecto://supabase_admin:@db:/_supabase
            - name: ERL_AFLAGS
              value: -proto_dist inet_tcp
            - name: METRICS_JWT_SECRET
            - name: POOLER_DEFAULT_POOL_SIZE
            - name: POOLER_MAX_CLIENT_CONN
            - name: POOLER_POOL_MODE
              value: transaction
            - name: POOLER_TENANT_ID
            - name: PORT
              value: "4000"
            - name: POSTGRES_DB
            - name: POSTGRES_PASSWORD
            - name: POSTGRES_PORT
            - name: REGION
              value: local
            - name: SECRET_KEY_BASE
            - name: VAULT_ENC_KEY
          image: supabase/supavisor:2.5.1
          livenessProbe:
            exec:
              command:
                - curl
                - -sSfL
                - --head
                - -o
                - /dev/null
                - http://127.0.0.1:4000/api/health
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          name: supabase-pooler
          ports:
            - containerPort: 5432
              protocol: TCP
            - containerPort: 6543
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/pooler/pooler.exs
              name: supavisor-claim0
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: supavisor-claim0
          persistentVolumeClaim:
            claimName: supavisor-claim0
            readOnly: true
