// Auto-generated docs registry
// This file is generated by scripts/generate-docs-registry.js during prebuild

import ethics from '../assets/docs/ethics.md';
import home from '../assets/docs/index.md';
import workflows_image_processing from '../assets/docs/workflows/image-processing.md';
import workflows from '../assets/docs/workflows/index.md';

export const docsModules = {
  'ethics': ethics,
  'home': home,
  'workflows/image-processing': workflows_image_processing,
  'workflows': workflows
};

export const docsMetadata = [
  {
    slug: 'ethics',
    filePath: 'ethics.md',
    category: 'general'
  },
  {
    slug: 'home',
    filePath: 'index.md',
    category: 'general'
  },
  {
    slug: 'workflows/image-processing',
    filePath: 'workflows/image-processing.md',
    category: 'workflows'
  },
  {
    slug: 'workflows',
    filePath: 'workflows/index.md',
    category: 'workflows'
  }
];

export type DocMetadata = {
  slug: string;
  filePath: string;
  category: string;
};
